package com.stevecc.topgithubrepos.api.search

import io.reactivex.rxjava3.core.Single
import retrofit2.http.GET
import retrofit2.http.Query

/*
 * Service to access the GitHub Search API: https://docs.github.com/en/rest/reference/search
 * Implementation generated by Retrofit
 */
interface SearchService {
    companion object {
        const val BASE_URL = "search"
    }

    // https://docs.github.com/en/rest/reference/search#search-repositories
    @GET("${BASE_URL}/repositories")
    fun repositories(
        @Query("q") searchQuery: String,
        @Query("per_page") perPageCount: Int
    ): Single<RepositoryResults>
}
